### ISSUE TITLE
PDFs for non-US printing

### ISSUE THREAD

**Issue by Munksgaard** [ianstormtaylor/hpmor#3]
Hi,

The British Lulu site does not allow you to chose the US Trade (6" x 9") size for the premium paperbacks. Is it possible to get a PDF file in another size, such as A5 or Royal?

**Comment by ianstormtaylor** [comment]
Hey @Munksgaard, sorry for the long delay here, but the PDF's I'm sure could be reformatted—I honestly can't remember where I got them from. Good luck!
